apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web
spec:
  containers:
    - name: web-server
      image: reallinux/web-server:1
      ports:
        - containerPort: 80
          protocol: TCP