apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: webapp
spec:
  containers:
    - name: web-server
      image: reallinux/web-server:1
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80   
      protocol: TCP
      nodePort: 31000
  selector:
    app: webapp
