apiVersion:
kind:
metadata:
  name:
  labels:
    app:
spec:
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:    
      containers:
      - name:
        image:
        volumeMounts:
        - mountPath:
          name:
      volumes:
      - name:
        hostPath:
          path: 
        
    