apiVersion: v1
kind: LimitRange
metadata:
  name: limits-dev2
  namespace: dev2
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 2Gi
    min:
      storage: 1Gi
  - type: Container
    