apiVersion: v1
kind: Pod
metadata:
  name: liveness-httpget
  labels:
    run: liveness-httpget
spec:
  containers:
  - name: healthz-nginx
    image: sysnet4admin/healthz-nginx
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
        httpHeaders:
        - name: purpose
          value: health-check
      initialDelaySeconds: 3
      periodSeconds: 3