apiVersion: v1
kind: Pod
metadata:
  labels:
    run: liveness-exec
  name: liveness-exec
spec:
  containers:
  - name: tardy-nginx
    image: sysnet4admin/tardy-nginx
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy-on
      initialDelaySeconds: 10
      periodSeconds: 10         # it cannot start Property 