apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multiple-command-v3
  name: multiple-command-v3
spec:
  containers:
  - image: sysnet4admin/net-tools
    name: net-tools
    command:
    - "/bin/sh"
    - "-c"
    - |
      echo run multiple-command-v3
      sleep 3600
