# w3-affinity-leader.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sleepy
    affinity: leader
  name: w3-affinity-leader
spec:
  containers:
  - image: sysnet4admin/sleepy
    name: sleepy
  nodeSelector:
    kubernetes.io/hostname: w3-k8s


